/**
 * Exemples valides (un par type d'exercice) et mini-taxonomie cohérente,
 * utilisés par les tests du schéma et du script de validation.
 */
import type { z } from 'zod'
import type { ExerciseInput, ExerciseType, taxonomySchema } from '../schema.ts'

export const exampleTaxonomy = {
  version: '2026.1',
  program_ref: 'Arrêté du 22 décembre 2014, annexe II (programme du DSCG)',
  sources: [{ label: 'Légifrance', url: 'https://www.legifrance.gouv.fr/' }],
  ues: [
    {
      id: 'UE4',
      slug: 'ue4-compta-audit',
      title: 'Comptabilité et audit',
      weight: 3,
      target_v1: 700,
      exam: { duration_minutes: 240, coefficient: 1.5, ects: 30, format: 'Étude de cas' },
      themes: [
        {
          id: 'ifrs',
          title: 'Normes IFRS',
          official: true,
          notions: [
            { id: 'ias-16-immobilisations', title: 'IAS 16 — Immobilisations corporelles', refs: ['IAS 16'] },
            { id: 'ifrs-16-contrats-location', title: 'IFRS 16 — Contrats de location', refs: ['IFRS 16'] },
          ],
        },
        {
          id: 'audit',
          title: 'Audit',
          official: true,
          notions: [
            {
              id: 'cycle-ventes-clients',
              title: 'Cycle ventes-clients',
              refs: ['NEP 315', 'NEP 500'],
              group: 'ventes-clients',
              group_title: 'Ventes-clients',
            },
          ],
        },
        {
          id: 'consolidation',
          title: 'Consolidation',
          official: true,
          notions: [{ id: 'perimetre-et-methodes', title: 'Périmètre et méthodes', refs: ['IFRS 10', 'IFRS 11'] }],
        },
        {
          id: 'pcg',
          title: 'PCG et comptes annuels',
          official: true,
          notions: [{ id: 'pcg-achats', title: 'Achats et charges externes', refs: ['PCG art. 946-60'] }],
        },
      ],
    },
    {
      id: 'UE2',
      slug: 'ue2-finance',
      title: 'Finance',
      weight: 3,
      target_v1: 250,
      exam: { duration_minutes: 180, coefficient: 1.5, ects: 15, format: null },
      themes: [
        {
          id: 'investissement',
          title: 'Choix d’investissement',
          official: true,
          notions: [{ id: 'van-tri', title: 'VAN et TRI', refs: [] }],
        },
      ],
    },
  ],
} satisfies z.input<typeof taxonomySchema>

const base = {
  difficulty: 2 as const,
  tags: [] as string[],
  source_ref: 'IAS 16 §43-47',
  verified: true,
  estimated_seconds: 60,
  explanation: 'Correction détaillée.',
}

const ias16 = { ue: 'UE4', theme: 'ifrs', notion: 'ias-16-immobilisations' } as const

export const exampleExercises = {
  mcq: {
    ...base,
    ...ias16,
    id: 'ue4-ifrs-ias16-0042',
    type: 'mcq',
    tags: ['amortissement', 'composants'],
    statement: 'Selon IAS 16, comment amortir un avion dont les moteurs ont une durée d’utilité différente de la cellule ?',
    options: [
      'Un seul plan sur 20 ans',
      'Deux plans : moteurs sur 8 ans, cellule sur 20 ans',
      'Au choix de l’entité',
      'Un seul plan sur la durée moyenne pondérée',
    ],
    answer: [1],
    multiple: false,
  },
  true_false: {
    ...base,
    ...ias16,
    id: 'ue4-ifrs-ias16-0043',
    type: 'true_false',
    statement: 'La réévaluation d’une immobilisation corporelle peut être pratiquée bien par bien.',
    answer: false,
    justification: 'IAS 16 §36 : la réévaluation s’applique à toute la catégorie d’immobilisations.',
  },
  numeric: {
    ...base,
    id: 'ue2-invest-van-0001',
    type: 'numeric',
    ue: 'UE2',
    theme: 'investissement',
    notion: 'van-tri',
    source_ref: 'Formule de la VAN',
    statement: 'Investissement 1 000, flux de 600 pendant 2 ans, taux 10 %. VAN ?',
    expected_value: 41.32,
    tolerance: { kind: 'relative', value: 0.01 },
    unit: '€',
    decimals: 2,
  },
  journal_entry: {
    ...base,
    id: 'ue4-pcg-achats-0001',
    type: 'journal_entry',
    ue: 'UE4',
    theme: 'pcg',
    notion: 'pcg-achats',
    source_ref: 'PCG comptes 607, 44566, 401',
    statement: 'Achat de marchandises 1 000 € HT, TVA 20 %, à crédit.',
    date: '2026-03-15',
    entries: [
      { account: '607', label: 'Achats de marchandises', debit: 1000, credit: 0 },
      { account: '44566', label: 'TVA déductible', debit: 200, credit: 0 },
      { account: '401', label: 'Fournisseurs', debit: 0, credit: 1200 },
    ],
  },
  case_study: {
    ...base,
    ...ias16,
    id: 'ue4-ifrs-ias16-cas-0001',
    type: 'case_study',
    estimated_seconds: 900,
    title: 'Acquisition d’une machine',
    context: 'La société X acquiert une machine 100 000 € HT le 1er janvier N, durée d’utilité 5 ans.',
    total_points: 10,
    sub_questions: [
      {
        id: 'q1',
        kind: 'mcq',
        prompt: 'Quel mode d’amortissement par défaut ?',
        points: 2,
        options: ['Linéaire', 'Dégressif', 'Aucun'],
        answer: [0],
      },
      {
        id: 'q2',
        kind: 'numeric',
        prompt: 'Dotation de l’exercice N ?',
        points: 3,
        expected_value: 20000,
        tolerance: { kind: 'absolute', value: 1 },
        unit: '€',
      },
      {
        id: 'q3',
        kind: 'journal_entry',
        prompt: 'Écriture de dotation',
        points: 3,
        entries: [
          { account: '68112', label: 'Dotation', debit: 20000, credit: 0 },
          { account: '28154', label: 'Amortissement matériel', debit: 0, credit: 20000 },
        ],
      },
      {
        id: 'q4',
        kind: 'open',
        prompt: 'Justifiez le choix du mode.',
        points: 2,
        model_answer: 'Le mode reflète le rythme de consommation des avantages économiques (IAS 16 §60).',
        key_points: ['rythme de consommation', 'IAS 16 §60'],
        explanation: 'À défaut d’autre rythme, le linéaire s’impose.',
      },
    ],
  },
  consolidation_case: {
    ...base,
    id: 'ue4-conso-perimetre-0001',
    type: 'consolidation_case',
    ue: 'UE4',
    theme: 'consolidation',
    notion: 'perimetre-et-methodes',
    source_ref: 'IFRS 10 §7',
    estimated_seconds: 1200,
    title: 'Groupe M',
    context: 'M détient 80 % de A, qui détient 60 % de B.',
    entities: [
      { id: 'mere', name: 'M', is_parent: true },
      { id: 'fille-a', name: 'A' },
      { id: 'fille-b', name: 'B' },
    ],
    links: [
      { from: 'mere', to: 'fille-a', ownership_pct: 80, voting_pct: 80 },
      { from: 'fille-a', to: 'fille-b', ownership_pct: 60 },
    ],
    steps: [
      {
        id: 'methode-b',
        stage: 'methode',
        kind: 'mcq',
        prompt: 'Méthode de consolidation de B ?',
        points: 2,
        options: ['Intégration globale', 'Mise en équivalence', 'Exclusion'],
        answer: [0],
      },
      {
        id: 'interet-b',
        stage: 'pourcentages',
        kind: 'numeric',
        prompt: 'Pourcentage d’intérêt de M dans B ?',
        points: 2,
        expected_value: 48,
        tolerance: { kind: 'absolute', value: 0 },
        unit: '%',
      },
      {
        id: 'controle-b',
        stage: 'pourcentages',
        kind: 'true_false',
        prompt: 'Le pourcentage de contrôle de M dans B est de 60 %.',
        points: 1,
        answer: true,
      },
    ],
  },
  audit_case: {
    ...base,
    id: 'ue4-audit-ventes-0001',
    type: 'audit_case',
    ue: 'UE4',
    theme: 'audit',
    notion: 'cycle-ventes-clients',
    source_ref: 'NEP 500, NEP 505',
    estimated_seconds: 600,
    title: 'Séparation des exercices',
    cycle: 'ventes-clients',
    situation: 'Forte hausse des ventes sur les derniers jours de l’exercice.',
    assertions: ['séparation des exercices', 'réalité'],
    procedures: {
      options: [
        'Tester les livraisons autour de la clôture',
        'Circulariser les clients',
        'Recompter les immobilisations',
        'Analyser les avoirs émis après la clôture',
      ],
      answer: [0, 1, 3],
    },
    risk: { options: ['faible', 'modéré', 'élevé'], answer: 2, rationale: 'Pic atypique de chiffre d’affaires.' },
    conclusion: {
      model_answer: 'Les ventes sont correctement rattachées à l’exercice, sous réserve des tests réalisés.',
      key_points: ['cut-off', 'avoirs post-clôture'],
    },
    points: 6,
  },
  flashcard: {
    ...base,
    ...ias16,
    id: 'ue4-ifrs-ias16-fc-0001',
    type: 'flashcard',
    front: 'Approche par composants (IAS 16)',
    back: 'Chaque partie significative à durée d’utilité différente est amortie séparément.',
  },
} satisfies { [K in ExerciseType]: Extract<ExerciseInput, { type: K }> }
