/**
 * Comptes usuels du plan comptable général (règl. ANC 2014-03, plan de comptes du PCG consolidé au
 * 1er janvier 2026, après le règl. ANC 2022-06), pour l'aide à la saisie des écritures. Liste indicative, non exhaustive :
 * un compte absent reste saisissable.
 */
export interface PcgAccount {
  number: string
  label: string
}

export const PCG_ACCOUNTS: readonly PcgAccount[] = [
  { number: '101', label: 'Capital' },
  { number: '1011', label: 'Capital souscrit – non appelé' },
  { number: '1012', label: 'Capital souscrit – appelé, non versé' },
  { number: '1013', label: 'Capital souscrit – appelé, versé' },
  { number: '104', label: 'Primes liées au capital social' },
  { number: '1041', label: "Primes d'émission" },
  { number: '1042', label: 'Primes de fusion' },
  { number: '1043', label: "Primes d'apport" },
  { number: '105', label: 'Écarts de réévaluation' },
  { number: '106', label: 'Réserves' },
  { number: '1061', label: 'Réserve légale' },
  { number: '1068', label: 'Autres réserves' },
  { number: '109', label: 'Actionnaires : capital souscrit – non appelé' },
  { number: '110', label: 'Report à nouveau (solde créditeur)' },
  { number: '119', label: 'Report à nouveau (solde débiteur)' },
  { number: '120', label: "Résultat de l'exercice (bénéfice)" },
  { number: '129', label: "Résultat de l'exercice (perte)" },
  { number: '131', label: "Subventions d'équipement" },
  { number: '139', label: "Subventions d'investissement inscrites au compte de résultat" },
  { number: '145', label: 'Amortissements dérogatoires' },
  { number: '151', label: 'Provisions pour risques' },
  { number: '1511', label: 'Provisions pour litiges' },
  { number: '1514', label: 'Provisions pour amendes et pénalités' },
  { number: '1515', label: 'Provisions pour pertes de change' },
  { number: '1516', label: 'Provisions pour pertes sur contrats' },
  { number: '1518', label: 'Autres provisions pour risques' },
  { number: '152', label: 'Provisions pour charges' },
  { number: '1521', label: 'Provisions pour pensions et obligations similaires' },
  { number: '1522', label: 'Provisions pour restructurations' },
  { number: '1523', label: 'Provisions pour impôts' },
  { number: '1525', label: 'Provisions pour gros entretien ou grandes révisions' },
  { number: '1526', label: 'Provisions pour remise en état' },
  { number: '1527', label: 'Autres provisions pour charges' },
  { number: '161', label: 'Emprunts obligataires convertibles' },
  { number: '163', label: 'Autres emprunts obligataires' },
  { number: '164', label: 'Emprunts auprès des établissements de crédit' },
  { number: '1661', label: 'Participation des salariés – comptes bloqués' },
  { number: '168', label: 'Autres emprunts et dettes assimilées' },
  { number: '169', label: 'Primes de remboursement des obligations' },
  { number: '201', label: "Frais d'établissement" },
  { number: '203', label: 'Frais de recherche et de développement' },
  { number: '205', label: 'Concessions, brevets, licences, logiciels' },
  { number: '207', label: 'Fonds commercial' },
  { number: '211', label: 'Terrains' },
  { number: '213', label: 'Constructions' },
  { number: '2154', label: 'Matériel industriel' },
  { number: '2182', label: 'Matériel de transport' },
  { number: '2183', label: 'Matériel de bureau et informatique' },
  { number: '2184', label: 'Mobilier' },
  { number: '2187', label: 'Agencements et aménagements divers' },
  { number: '231', label: 'Immobilisations corporelles en cours' },
  { number: '238', label: 'Avances et acomptes sur immobilisations corporelles' },
  { number: '261', label: 'Titres de participation' },
  { number: '267', label: 'Créances rattachées à des participations' },
  { number: '271', label: 'Titres immobilisés (droit de propriété)' },
  { number: '274', label: 'Prêts' },
  { number: '275', label: 'Dépôts et cautionnements versés' },
  { number: '2805', label: 'Amortissements des concessions, brevets, logiciels' },
  { number: '2807', label: 'Amortissements du fonds commercial' },
  { number: '2813', label: 'Amortissements des constructions' },
  { number: '28154', label: 'Amortissements du matériel industriel' },
  { number: '28182', label: 'Amortissements du matériel de transport' },
  { number: '28183', label: 'Amortissements du matériel de bureau et informatique' },
  { number: '2905', label: 'Dépréciations des concessions, brevets, logiciels' },
  { number: '2907', label: 'Dépréciations du fonds commercial' },
  { number: '2911', label: 'Dépréciations des terrains' },
  { number: '2961', label: 'Dépréciations des titres de participation' },
  { number: '2971', label: 'Dépréciations des titres immobilisés' },
  { number: '31', label: 'Matières premières' },
  { number: '355', label: 'Produits finis' },
  { number: '37', label: 'Stocks de marchandises' },
  { number: '391', label: 'Dépréciations des matières premières' },
  { number: '397', label: 'Dépréciations des stocks de marchandises' },
  { number: '401', label: 'Fournisseurs' },
  { number: '403', label: 'Fournisseurs – effets à payer' },
  { number: '404', label: "Fournisseurs d'immobilisations" },
  { number: '408', label: 'Fournisseurs – factures non parvenues' },
  { number: '4091', label: 'Fournisseurs – avances et acomptes versés' },
  { number: '411', label: 'Clients' },
  { number: '413', label: 'Clients – effets à recevoir' },
  { number: '416', label: 'Clients douteux ou litigieux' },
  { number: '4181', label: 'Clients – factures à établir' },
  { number: '4191', label: 'Clients – avances et acomptes reçus' },
  { number: '421', label: 'Personnel – rémunérations dues' },
  { number: '4246', label: 'Réserve spéciale de participation' },
  { number: '431', label: 'Sécurité sociale' },
  { number: '437', label: 'Autres organismes sociaux' },
  { number: '4386', label: 'Organismes sociaux – autres charges à payer' },
  { number: '441', label: 'État – subventions à recevoir' },
  { number: '444', label: 'État – impôts sur les bénéfices' },
  { number: '4452', label: 'TVA due intracommunautaire' },
  { number: '4455', label: 'TVA à décaisser' },
  { number: '44562', label: 'TVA déductible sur immobilisations' },
  { number: '44566', label: 'TVA déductible sur autres biens et services' },
  { number: '44567', label: 'Crédit de TVA à reporter' },
  { number: '4457', label: 'TVA collectée' },
  { number: '44571', label: 'TVA collectée' },
  { number: '44586', label: 'TVA sur factures non parvenues' },
  { number: '44587', label: 'TVA sur factures à établir' },
  { number: '447', label: 'Autres impôts, taxes et versements assimilés' },
  { number: '451', label: 'Groupe' },
  { number: '455', label: 'Associés – comptes courants' },
  { number: '456', label: 'Associés – opérations sur le capital' },
  { number: '4562', label: 'Apporteurs – capital appelé, non versé' },
  { number: '457', label: 'Associés – dividendes à payer' },
  { number: '462', label: "Créances sur cessions d'immobilisations" },
  { number: '467', label: 'Autres comptes débiteurs ou créditeurs' },
  { number: '471', label: "Comptes d'attente" },
  { number: '476', label: 'Différences de conversion – actif' },
  { number: '477', label: 'Différences de conversion – passif' },
  { number: '481', label: 'Charges à répartir sur plusieurs exercices' },
  { number: '486', label: "Charges constatées d'avance" },
  { number: '487', label: "Produits constatés d'avance" },
  { number: '491', label: 'Dépréciations des comptes de clients' },
  { number: '503', label: 'Actions' },
  { number: '506', label: 'Obligations' },
  { number: '508', label: 'Autres valeurs mobilières de placement' },
  { number: '512', label: 'Banque' },
  { number: '519', label: 'Concours bancaires courants' },
  { number: '5181', label: 'Intérêts courus à payer' },
  { number: '52', label: 'Instruments financiers à terme et jetons détenus' },
  { number: '53', label: 'Caisse' },
  { number: '58', label: 'Virements internes' },
  { number: '590', label: 'Dépréciations des valeurs mobilières de placement' },
  { number: '601', label: 'Achats de matières premières' },
  { number: '6031', label: 'Variation des stocks de matières premières' },
  { number: '6037', label: 'Variation des stocks de marchandises' },
  { number: '604', label: "Achats d'études et prestations de services" },
  { number: '606', label: 'Achats non stockés de matières et fournitures' },
  { number: '607', label: 'Achats de marchandises' },
  { number: '613', label: 'Locations' },
  { number: '615', label: 'Entretien et réparations' },
  { number: '616', label: "Primes d'assurance" },
  { number: '622', label: 'Rémunérations d’intermédiaires et honoraires' },
  { number: '6225', label: 'Rémunérations d’affacturage' },
  { number: '6226', label: 'Honoraires' },
  { number: '627', label: 'Services bancaires et assimilés' },
  { number: '631', label: 'Impôts, taxes et versements assimilés sur rémunérations' },
  { number: '635', label: 'Autres impôts, taxes et versements assimilés' },
  { number: '641', label: 'Rémunérations du personnel' },
  { number: '645', label: 'Charges de sécurité sociale et de prévoyance' },
  { number: '654', label: 'Pertes sur créances irrécouvrables' },
  { number: '657', label: 'Valeurs comptables des immobilisations incorporelles et corporelles cédées' },
  { number: '6581', label: 'Pénalités sur marchés et dédits payés' },
  { number: '6582', label: 'Pénalités, amendes fiscales et pénales' },
  { number: '661', label: 'Charges d’intérêts' },
  { number: '6611', label: 'Intérêts des emprunts et dettes' },
  { number: '666', label: 'Pertes de change' },
  { number: '6671', label: 'Valeurs comptables des immobilisations financières cédées' },
  { number: '668', label: 'Autres charges financières' },
  { number: '678', label: 'Autres charges exceptionnelles' },
  { number: '681', label: 'Dotations aux amortissements, dépréciations et provisions – exploitation' },
  { number: '6811', label: 'Dotations aux amortissements des immobilisations' },
  { number: '6815', label: 'Dotations aux provisions d’exploitation' },
  { number: '6816', label: 'Dotations aux dépréciations des immobilisations' },
  { number: '6817', label: 'Dotations aux dépréciations des actifs circulants' },
  { number: '686', label: 'Dotations aux amortissements, dépréciations et provisions – financières' },
  { number: '6865', label: 'Dotations aux provisions financières' },
  { number: '6866', label: 'Dotations aux dépréciations des éléments financiers' },
  { number: '687', label: 'Dotations aux amortissements, dépréciations et provisions – exceptionnelles' },
  { number: '6872', label: 'Dotations aux provisions réglementées (amortissements dérogatoires)' },
  { number: '691', label: 'Participation des salariés' },
  { number: '695', label: 'Impôts sur les bénéfices' },
  { number: '698', label: 'Intégration fiscale' },
  { number: '699', label: 'Produits – reports en arrière des déficits' },
  { number: '701', label: 'Ventes de produits finis' },
  { number: '706', label: 'Prestations de services' },
  { number: '707', label: 'Ventes de marchandises' },
  { number: '709', label: 'Rabais, remises et ristournes accordés' },
  { number: '7135', label: 'Variation des stocks de produits' },
  { number: '74', label: "Subventions d'exploitation" },
  { number: '747', label: "Quote-part des subventions d'investissement virée au résultat" },
  { number: '757', label: 'Produits des cessions d’immobilisations incorporelles et corporelles' },
  { number: '7581', label: 'Dédits et pénalités perçus' },
  { number: '761', label: 'Produits de participations' },
  { number: '764', label: 'Revenus des valeurs mobilières de placement' },
  { number: '766', label: 'Gains de change' },
  { number: '7671', label: 'Produits des cessions d’immobilisations financières' },
  { number: '768', label: 'Autres produits financiers' },
  { number: '778', label: 'Autres produits exceptionnels' },
  { number: '781', label: 'Reprises sur amortissements, dépréciations et provisions – exploitation' },
  { number: '7815', label: 'Reprises sur provisions d’exploitation' },
  { number: '7816', label: 'Reprises sur dépréciations des immobilisations' },
  { number: '7817', label: 'Reprises sur dépréciations des actifs circulants' },
  { number: '786', label: 'Reprises sur provisions et dépréciations – financières' },
  { number: '7866', label: 'Reprises sur dépréciations des éléments financiers' },
  { number: '787', label: 'Reprises sur provisions et dépréciations – exceptionnelles' },
  { number: '7875', label: 'Reprises sur provisions réglementées' },
]

const byNumber = new Map(PCG_ACCOUNTS.map((a) => [a.number, a]))

/** Libellé d'un compte exact, ou de son compte parent le plus proche dans la liste (« 2154 » → 2154 ; « 21540 » → 2154). */
export function pcgLabel(account: string): string | undefined {
  for (let n = account; n.length >= 2; n = n.slice(0, -1)) {
    const hit = byNumber.get(n)
    if (hit) return hit.label
  }
  return undefined
}
